from abc import abstractmethod
from jinja2 import Template
from pathlib import Path
from src.util import camel_snake


class TemplateBasePreProcessor:
    def __init__(self) -> None:
        pass

    def write_file(self, pre_processor_dir: Path) -> Path:
        if not pre_processor_dir.exists():
            pre_processor_dir.mkdir(parents=True, exist_ok=True)
        file_name = self._get_file_name()
        full_path = pre_processor_dir / file_name
        content = self._get_content()
        processed_content = self._get_processed_content(content)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(processed_content)
        return full_path

    @abstractmethod
    def get_template_type(self) -> str:
        pass

    def _get_file_name(self) -> str:
        tt = self.get_template_type()
        return f"process_{tt}_template.py"

    def _get_processed_content(self, content: str) -> str:
        template_type = self.get_template_type()
        class_name = camel_snake.to_camel_case(f"process_{template_type}_template")
        template: Template = Template(source=content)
        processed_content = template.render(
            class_name=class_name,
            render_class=self.__class__.__name__,
            template_type=template_type,
        )
        return processed_content

    def _get_content(self) -> str:
        content = """# Auto-generated pre-processor for {{ template_type }} template.
# This file is generated by {{ render_class }} and should not be edited manually.

from typing import Any
from src.template.front_mater_meta import FrontMatterMeta


class {{ class_name }}:
    def __init__(self, *, template_content: str, monad_name: str, **kwargs: Any):
        self.template_content = template_content
        self.monad_name = monad_name
        self._kwargs = kwargs

    def get_template_type(self) -> str:
        \"\"\"Return the type of the template being processed.\"\"\"
        return "{{ template_type }}"

    def _format(self) -> FrontMatterMeta:
        # Process and format the glyph template content
        fm = FrontMatterMeta.from_content(self.template_content)
        if fm.has_field("artifact_activator"):
            fm.frontmatter["artifact_activator"] = [
                self.monad_name,
                "[[prompt:Other Console Members or Witnesses]]",
            ]
        if fm.has_field("contributor"):
            fm.frontmatter["contributor"] = [
                f"[[prompt:{self.monad_name} or other Console Member]]`"
            ]
        keys = {"rendered_by"}
        for key in keys:
            if key in self._kwargs and fm.has_field(key):
                fm.frontmatter[key] = self._kwargs[key]
        return fm

    def render(self) -> str:
        # Render the {{ template_type }} template with the provided context
        formatted = self._format()
        return formatted.get_template_text()

"""

        return content
