from typing import Any
from typing import Protocol
from api.lib.util.result import Result
from src.template.front_mater_meta import FrontMatterMeta
from .shared_rule_cache import SharedRuleCache


class ProtocolUpgradeRule(Protocol):
    def __init__(self, shared_cache: SharedRuleCache) -> None: ...
    def get_rule_id(self) -> str: ...
    def get_description(self) -> str: ...
    def get_order(self) -> int: ...
    def should_run(self, fm_artifact, fm_template, registry) -> bool: ...
    def shared_set(self, key: str, value: Any) -> None: ...
    def shared_get(self, key: str, default: Any = None) -> Any: ...
    def apply(
        self,
        fm_artifact: FrontMatterMeta,
        fm_template: FrontMatterMeta,
        registry: dict[str, Any],
    ) -> Result[FrontMatterMeta, None] | Result[None, Exception]: ...
    @property
    def shared_cache(self) -> SharedRuleCache: ...
    @property
    def rule_name(self) -> str: ...
