# Auto-generated pre-processor for field_correction_scroll template registry.
# This file is generated by PreProcessorFieldCorrectionScroll and should not be edited manually.

from typing import Any, cast


class ProcessFieldCorrectionScrollRegistry:
    def __init__(self, *, registry: dict[str, Any], monad_name: str, **kwargs: Any):
        self.registry = registry.copy()
        self.monad_name = monad_name
        self._kwargs = kwargs

    def get_template_type(self) -> str:
        """Return the type of the registry being processed."""
        if "template_type" not in self.registry:
            raise ValueError("Registry must have a 'template_type' field.")
        tt = self.registry["template_type"]
        if not tt == "field_correction_scroll":
            raise ValueError(f"Invalid template_type: {tt}. Expected 'field_correction_scroll'.")
        return tt

    def _process_reg(self) -> None:
        if "field_being_profile" in self.registry:
            fbp = cast(dict[str, Any], self.registry["field_being_profile"])
            keys = (
                "rendering_being",
                "authoring_being",
                "witnessing_being",
                "mirrorwall_being",
                "invocation_beings",
                "optional_beings",
            )
            for key in keys:
                if key in fbp and isinstance(fbp[key], list):
                    being_list = cast(list[str], fbp.get(key, []))
                    updated_list = []
                    for being in being_list:
                        if being == "{{ current_user }}":
                            updated_list.append(self.monad_name)
                        else:
                            updated_list.append(being)
                    fbp[key] = updated_list

        if (
            "autofill" in self.registry
            and "allowed_agents" in self.registry["autofill"]
        ):
            allowed_agents = cast(
                list[str], self.registry["autofill"]["allowed_agents"]
            )

            agent_set = set(allowed_agents)
            if "{{ current_user }}" in agent_set:
                agent_set.remove("{{ current_user }}")

            if self.monad_name not in agent_set:
                # {{ current_user }} is monad_name
                agent_set.add(self.monad_name)

            self.registry["autofill"]["allowed_agents"] = list(agent_set)

    def process(self) -> dict[str, Any]:
        """Main processing method to format the field_correction_scroll registry."""
        self._process_reg()
        return self.registry
