# Auto-generated pre-processor for field_correction_scroll template.
# This file is generated by PreProcessorFieldCorrectionScroll and should not be edited manually.

from typing import Any
from src.template.front_mater_meta import FrontMatterMeta


class ProcessFieldCorrectionScrollTemplate:
    def __init__(self, *, template_content: str, monad_name: str, **kwargs: Any):
        self.template_content = template_content
        self.monad_name = monad_name
        self._kwargs = kwargs

    def get_template_type(self) -> str:
        """Return the type of the template being processed."""
        return "field_correction_scroll"

    def _format(self) -> FrontMatterMeta:
        # Process and format the field_correction_scroll template content
        fm = FrontMatterMeta.from_content(self.template_content)
        return fm

    def render(self) -> str:
        # Render the field_correction_scroll template with the provided context
        formatted = self._format()
        return formatted.get_template_text()
