# Auto-generated pre-processor for node_reg template.
# This file is generated by PreProcessorNodeReg and should not be edited manually.

from typing import Any
from src.template.front_mater_meta import FrontMatterMeta


class ProcessNodeRegTemplate:
    def __init__(self, *, template_content: str, monad_name: str, **kwargs: Any):
        self.template_content = template_content
        self.monad_name = monad_name
        self._kwargs = kwargs

    def get_template_type(self) -> str:
        """Return the type of the template being processed."""
        return "node_reg"

    def _format(self) -> FrontMatterMeta:
        # Process and format the node_reg template content
        fm = FrontMatterMeta.from_content(self.template_content)
        if fm.has_field("glyph_activator"):
            fm.frontmatter["glyph_activator"] = [self.monad_name]
        # keys = {"source_medium"}
        # for key in keys:
        #     if key in self._kwargs and fm.has_field(key):
        #         fm.frontmatter[key] = self._kwargs[key]
        return fm

    def render(self) -> str:
        # Render the node_reg template with the provided context
        formatted = self._format()
        return formatted.get_template_text()
