from fastapi.openapi.utils import get_openapi
from fastapi.openapi.docs import get_redoc_html, get_swagger_ui_html
from fastapi import FastAPI
from fastapi import Depends
from api.models.descope.descope_session import DescopeSession
from api.lib.descope.session import get_descope_session


# region Protected API Routes


def register_doc_routes(app: FastAPI):

    @app.get(
        "/openapi.json",
        include_in_schema=False,
        operation_id="openapi_schema",
        tags=["Documentation"],
    )
    async def openapi_schema(
        session_user: DescopeSession = Depends(get_descope_session),
    ):
        """Generate the OpenAPI schema for the application.
        Parameters
        ----------
        credentials : HTTPAuthorizationCredentials, optional
            Authorization credentials provided by the configured security dependency.
        Returns
        -------
        dict
            The OpenAPI specification describing the registered API routes.
        """

        data = get_openapi(
            title="Codex Templates API", version="1.0.0", routes=app.routes
        )
        if not data.get("security"):
            data["security"] = [{"bearerAuth": []}]
        return data

    @app.get(
        "/docs",
        include_in_schema=False,
        operation_id="docs_ui",
        tags=["Documentation"],
    )
    async def docs_ui(session_user: DescopeSession = Depends(get_descope_session)):
        """Render the Swagger UI for authenticated users or return a redirect response when authentication is required.
        Parameters
        ----------
        user : Any
            Result from the `_require_login_or_redirect` dependency, which may be a user object or a `RedirectResponse`.
        Returns
        -------
        HTMLResponse | RedirectResponse
            Swagger UI HTML response when authenticated, otherwise the redirect response.
        """

        html_response = get_swagger_ui_html(
            openapi_url="/openapi.json",
            title="Codex Templates API Docs",
        )
        if session_user.access_token:
            html_response.headers["Authorization"] = (
                f"Bearer {session_user.access_token}"
            )
        return html_response

    @app.get(
        "/redoc",
        include_in_schema=False,
        operation_id="redoc_ui",
        tags=["Documentation"],
    )
    async def redoc_ui(session_user: DescopeSession = Depends(get_descope_session)):
        """
        Return the ReDoc HTML page for the OpenAPI schema, respecting custom prefix settings.
        Parameters
        ----------
        credentials : fastapi.security.HTTPAuthorizationCredentials
            Authorization credentials extracted via the configured security dependency.
        Returns
        -------
        str
            HTML markup generated by `fastapi.openapi.docs.get_redoc_html` for the configured OpenAPI endpoint.
        """

        return get_redoc_html(
            openapi_url="/openapi.json",
            title="ReDoc",
        )

    # endregion Protected API Routes
